### ISSUE TITLE
Move decade heading and decade nav out of map tile.

### ISSUE THREAD

**Issue by wlla** [nypl-spacetime/maps-by-decade#85]
In [Map browse](http://spacetime.nypl.org/mbd-test/#/1870) 

Move decade heading out of map tile div and make decade heading h1.
Move prev decade and next decade links out of the <div> map tile div.

https://docs.google.com/a/nypl.org/document/d/1xHhy6qQfZhWq-KktV__cWSfCnPQtTe0fhapS_Ka2HWs/edit?disco=AAAAA8gQDsc

**Comment by bertspaan** [comment]
Decade heading is already out of map tile div. Where exactly should I move them?

**Comment by wlla** [comment]
@seanredmond additional details needed on reported bug; see above

**Comment by seanredmond** [comment]
`div.cQbSIk` should be the `h2` of the page (I said `h1` above but "Maps by Decade" in the header is the `h1`).

The parent `div` (the `div` that contains `.coAHgU`, `.gsiVJy`, and `.gszOzl`) should come at least before `div.hdKDHS` so that the semantic structure is something like

- Maps by decade
  - 1860-1869
    - prev/next
    - the map (leaflet container)

That would bump the titles of individual maps from `h2` to `h3`

![screen shot 2017-03-03 at 1 27 21 pm](https://cloud.githubusercontent.com/assets/720703/23563566/39fd3950-0015-11e7-947d-3aba6dfbd524.png)
